@startuml show remove
!define AzurePuml /home/ian/Documents/Azure-PlantUML-2.2/dist
!include AzurePuml/AzureCommon.puml
!include AzurePuml/Containers/AzureContainerRegistry.puml
!include AzurePuml/Containers/AzureContainerInstance.puml
!include AzurePuml/Containers/AzureServiceEnvironment.puml
!include AzurePuml/Databases/AzureSqlDatabase.puml
!include AzurePuml/Databases/AzureCosmosDb.puml
!include AzurePuml/DevOps/AzureRepos.puml
!include AzurePuml/DevOps/AzurePipelines.puml
!include AzurePuml/Networking/AzureVirtualNetwork.puml
!include AzurePuml/Storage/AzureStorageClassic.puml
!include AzurePuml/Networking/AzureServiceEndpoint.puml
!include AzurePuml/Containers/AzureContainerApp.puml
!include AzurePuml/DevOps/AzureTestPlans.puml
!include AzurePuml/Management/AzureUserPrivacy.puml


        AzureSqlDatabase(MovieselDatabase, "Movies","AzureHosted")
        AzureSqlDatabase(NoSqlDatabase, "Bookings and Tickets","in Container Memory")



    Package "Frontend" {
        AzureContainerApp(FrontendWeb, "Frotnend Web","1-2 Instances")
        AzureContainerApp(FrontendMitarbeiter, "Frontend Mitarbeiter","1 Instance")
    }


        AzureContainerApp(BackendBooking, "Backend Booking","1 Instances")
        AzureContainerApp(BackendLook, "Backend Movie selection","1 Instances")
        AzureContainerApp(BackendUser, "Backend User","1 Instances")
        AzureContainerApp(Idempotency, "Idempotency","1 Instances")
        AzureContainerApp(BackendMes, "Backend Messages","1 Instances")

FrontendMitarbeiter-->Idempotency:1 Register Operation 
FrontendMitarbeiter-->BackendLook :2 start Cancel Show
BackendLook-->Idempotency:3 Register Operation
BackendLook-->BackendBooking :4 start Cancel Show
BackendBooking-->Idempotency:5 Register Operation
BackendBooking-->BackendMes :6 Post Messages to Users Inbox
BackendBooking-->NoSqlDatabase :7 Save remove bookings
BackendBooking-->BackendLook :8 i informed X users and refund
BackendLook-->MovieselDatabase :9 Save remove show
BackendLook-->FrontendMitarbeiter :10 done

FrontendWeb-->BackendUser :1 Login
FrontendWeb-->BackendMes :2 Get Messages
FrontendWeb-->FrontendWeb: be dissapointed





@enduml



